general {
    lock_cmd = pidof hyprlock || hyprlock
    before_sleep_cmd = loginctl lock-session
    after_sleep_cmd = hyprctl dispatch dpms on
}

# Keyboard backlight off after 2.5 min
listener {
    timeout = 150
    on-timeout = brightnessctl -sd asus::kbd_backlight set 0
    on-resume = brightnessctl -rd asus::kbd_backlight
}

# Dim screen after 2 min — saves brightness first, then restores on resume
listener {
    timeout = 120
    on-timeout = brightnessctl --save s 10%
    on-resume = brightnessctl --restore
}

# Screen off after 10 min
listener {
    timeout = 600
    on-timeout = brightnessctl s 0%
    on-resume = brightnessctl --restore
}

# Suspend after 15 min
listener {
    timeout = 900
    on-timeout = systemctl suspend
}
