general {

	hide_cursor = false
	ignore_empty_input = true
	fail_timeout = 0

}

animations {
	enabled = true
	bezier = easeOutQuint,1,1,0,0
	animation = fade, 1, 1.73, easeOutQuint
	animation = fadeIn, 1, 3, easeOutQuint
	animation = fadeOut, 1, 1.73, easeOutQuint
}

background {
	blur_passes = 3
	blur_size = 3
	path = ~/.config/hypr/current_wallpaper.jpg
	brightness = .8
}

/* image {

	path = ~/Downloads/luffy.jpg
	size = 500
	position = 0,200
	border_size = 2
	border_color = rgba(0,0,0,1)

}
*/

input-field {
	size = 25%, 7%
	outline_thickness = 0
	inner_color = rgba(0, 0, 0, 0.0) # no file
	outer_color = rgba(0,0,0,1)
	check_color= rgba(155,0,0,0)
	fail_color=rgba(155,0,0,0)
	fail_text = Authentication Failed
	fail_timeout = 2
	capslock_color = rgba(155,0,155,0)
	font_family = Fira Sans Light
	font_color = rgb(200, 200, 200)
	fade_on_empty = false
	rounding = 15
	placeholder_text = Enter Password
	dots_size = 0.1
	dots_spacing = .15
	shadow_passes = 5
	shadow_size = 3	
	dots_center = true
	position = 0, -300
	
}

label {
    text = ________________________________________ # Or a single line of dashes
    color = rgba(255, 255, 255, 1) # Your desired line color
    font_family = Fira Code Light
    font_size = 15
    position = 0, -335 # Adjust this position to align with your input-field
    halign = center
    valign = center
}

label {
    text = cmd[update:1000]~/.config/hypr/hyprlock-scripts/hourscript.sh
    color = rgba(255,255,255,1)
    font_size = 256
    font_family = Fira Sans ExtraLight
    position = 0, 310
    halign = center
    valign = center
}



# Label for the minute
label {
    text = cmd[update:1000]~/.config/hypr/hyprlock-scripts/minutescript.sh
    color = rgba(255,255,255,1)
    font_size = 256
    font_family = Fira Sans Hair
    position = 0, -10
    halign = center
    valign = center
}

/*label {

	text = Ryan Holdstock
	color = rgba(255,255,255,1)
	font_size = 48
	font_family = Fira Sans Hair
	position = 0,-135
	halign = center
	valign = center
}
*/
