general {
	lock_cmd = pidof hyprlock || hyprlock
	before_sleep_cmd = loginctl lock-session
	after_sleep_cmd = hyprctl dispatch dpms on
}



listener {
	timeout = 150
	on-timeout = brightnessctl -sd asus::kbd_backlight set 0
	on-resume = brightnessctl -rd asus::kbd_backlight
}


#listener {
#    timeout = 300                                 # 5min
#    on-timeout = pidof hyprlock || hyprlock
#}

listener {
    timeout = 300
    brightness = brightnessctl g
    on-timeout = brightnessctl s brightness%
    on-resume = brightnessctl s brightness%
}

listener {
    timeout = 600                                                     # 5.5min
    on-timeout = brightnessctl s 0%                            # screen off when timeout has passed
    on-resume = brightnessctl s 30%          # screen on when activity is detected after timeout has fired.
}

listener {
    timeout = 900                                # 30min
    on-timeout = systemctl suspend                # suspend pc
