[General]
bookmarks=/home/rasberry
lastDisplay=0
maximizedWindow=true
savedPaths=/home/rasberry, /home/rasberry/Calibre Library, /home/rasberry/Desktop, /home/rasberry/Documents, /home/rasberry/Downloads, /home/rasberry/Music, /home/rasberry/Pictures, /home/rasberry/Projects, /home/rasberry/Public
windowGeometry=@Rect(560 252 800 576)
