[mgr]

prepend_keymap = [
	{ on = "k", run = "arrow prev", desc = "Previous file" },
	{ on = "j", run = "arrow next", desc = "Next file" },
	{ on = "h", run = "leave", desc = "Back to the parent directory" },
	{ on = "l", run = "enter", desc = "Enter the child directory" },
	{ on = "H", run = "back",    desc = "Back to previous directory" },
	{ on = "L", run = "forward", desc = "Forward to next directory" },
	{ on = "<K>", run = "arrow -15%", desc = "Seek up 5 units in the preview" },
	{ on = "<J>", run = "arrow 15%",  desc = "Seek down 5 units in the preview" },
	# { on = "", run = "arrow 15%",  desc = "Move cursor up half page" },
	# { on = "", run = "arrow -15%",   desc = "Move cursor down half page" },
	{ on = "<Space>", run = "toggle", desc = "Toggle the current selection state" },
	{ on = [ ",", "M" ], run = [ "sort mtime --reverse=no", "linemode mtime" ],  desc = "Sort by modified time" },
	{ on = [ ",", "m" ], run = [ "sort mtime --reverse=yes", "linemode mtime" ], desc = "Sort by modified time (reverse)" },
	{ on = [ "g", "s" ],       run = "cd /home/rasberry/School/classes",             desc = "Go to classes" },
  { on = [ "g", "S" ],       run = "cd /home/rasberry/mnt/schoolvm",             desc = "Go to classes" },
  { on = [ "g", "a" ],       run = "cd /home/rasberry/.local/share/applications",             desc = "Go to applications" },
  { on = [ "s", "s" ], run = "shell --block /home/rasberry/Scripts/sudoyazi.sh", desc = "Relaunch with sudo privileges"},
  { on = [ "s", "d" ], run = "shell 'ripdrag \"$@\" &' --confirm", desc="Drag and drop files"}
]

# [spot]
#
# prepend_keymap = [
# 	{ on = "i", run = "arrow prev", desc = "Previous line" },
# 	{ on = "k", run = "arrow next", desc = "Next line" },
# 	{ on = "j", run = "swipe prev", desc = "Swipe to previous file" },
# 	{ on = "l", run = "swipe next", desc = "Swipe to next file" },
# ]
#
# [tasks]
#
# prepend_keymap = [
# 	{ on = "i", run = "arrow prev", desc = "Previous task" },
# 	{ on = "k", run = "arrow next", desc = "Next task" },
# ]
#
# [pick]
#
# prepend_keymap = [
# 	{ on = "i", run = "arrow prev", desc = "Previous option" },
# 	{ on = "k", run = "arrow next", desc = "Next option" },
# ]
#
# [confirm]
#
# prepend_keymap = [
# 	{ on = "i", run = "arrow prev", desc = "Previous line" },
# 	{ on = "k", run = "arrow next", desc = "Next line" },
# ]
#
# [help]
#
# prepend_keymap = [
# 	{ on = "i", run = "arrow prev", desc = "Previous line" },
# 	{ on = "k", run = "arrow next", desc = "Next line" },
# ]
